### PR TITLE
ScannerMultiplexer: Removes concurrency due to bug

### LINKED ISSUE #682: v1.1.0: Specs fail unpredictably in ActiveAdmin / ruby 3.2/3.3 (no prism)
Hello,

after upgrading to v1.1.0, ActiveAdmin suite started having some flaky specs. This only seems to affect Ruby 3.2 and 3.3

## Minimum reproducible test case

```sh
BUNDLE_GEMFILE=gemfiles/rails_72/Gemfile CI=1 be rspec ./spec/locales/i18n_spec.rb[43:1] ./spec/unit/action_builder_spec.rb[1:3:1:1,1:3:2:1] -O .rspec_parallel --seed 10149
```

```
$ BUNDLE_GEMFILE=gemfiles/rails_72/Gemfile CI=1 be  rspec ./spec/locales/i18n_spec.rb[43:1] ./spec/unit/action_builder_spec.rb[1:3:1:1,1:3:2:1] -O .rspec_parallel --seed 10149
Run options:
  include {:focus=>true, :ids=>{"./spec/locales/i18n_spec.rb"=>["43:1"], "./spec/unit/action_builder_spec.rb"=>["1:3:1:1", "1:3:2:1"]}}
  exclude {:changes_filesystem=>true}

Randomized with seed 10149
.FF

Failures:

  1) defining actions from registration blocks when method with given name is already defined defining collection action writes warning to $stderr
     Failure/Error: expect($stderr.string).to include("Warning: method `process` already defined in Admin::PostsController")
       expected "" to include "Warning: method `process` already defined in Admin::PostsController"
     # ./spec/unit/action_builder_spec.rb:148:in `block (4 levels) in <top (required)>'
     # ./spec/support/shared_contexts/capture_stderr.rb:7:in `block (2 levels) in <top (required)>'

  2) defining actions from registration blocks when method with given name is already defined defining member action writes warning to $stderr
     Failure/Error: expect($stderr.string).to include("Warning: method `process` already defined in Admin::PostsController")
       expected "" to include "Warning: method `process` already defined in Admin::PostsController"
     # ./spec/unit/action_builder_spec.rb:136:in `block (4 levels) in <top (required)>'
     # ./spec/support/shared_contexts/capture_stderr.rb:7:in `block (2 levels) in <top (required)>'

Finished in 1.54 seconds (files took 1.83 seconds to load)
3 examples, 2 failures

Failed examples:

rspec ./spec/unit/action_builder_spec.rb:147 # defining actions from registration blocks when method with given name is already defined defining collection action writes warning to $stderr
rspec ./spec/unit/action_builder_spec.rb:135 # defining actions from registration blocks when method with given name is already defined defining member action writes warning to $stderr

Randomized with seed 10149
```

### Bisect

Bisected to #644 glebm/i18n-tasks@0c3697bebbfd52bd9bd2747f722c47a84e74d845

### PR DESCRIPTION
**Pull request by davidwessman**
- Fixes #682
- Release 1.1.0 started causing errors for active_admin, the test
  suite would be intermittently failing on Ruby 3.2 and 3.3.
- When calling `warn` it would fail to write any output, possibly
  due to thread safety issues with IO objects.
- This change removes the concurrency in ScannerMultiplexer,
  reverting to a sequential execution of the scanners.
- If we want parallelism in teh future we should consider writing
  something with Ractors, conrurrent-ruby or the parallel gem.

### CODE REVIEW

**Comment by glebm** [comment]
Odd that this started happening only now, perhaps there is a concurrency issue with one of the dependencies.
Falling back to serial makes sense for now.

File: lib/i18n/tasks/scanners/erb_ast_scanner.rb [hunk 1]
```diff
@@ -3,7 +3,6 @@
 require "i18n/tasks/scanners/ruby_scanner"
 require "i18n/tasks/scanners/local_ruby_parser"
 require "i18n/tasks/scanners/occurrence_from_position"
-require "prism"
```
Comment (chaadow) [inline lib/i18n/tasks/scanners/erb_ast_scanner.rb]: this line made my i18n-task fail like this:

image

Comment (davidwessman) [reply lib/i18n/tasks/scanners/erb_ast_scanner.rb]: Ah, will make a fix for it.

Comment (davidwessman) [reply lib/i18n/tasks/scanners/erb_ast_scanner.rb]: https://github.com/glebm/i18n-tasks/pull/689
