### PR TITLE
Fix key splitting failures if key contains any parenthesis char

### LINKED ISSUE #549: Bug: Missing key checks and normalization fail if keys contain single parenthesis characters
### Description
In case keys contain characters that can be used as parenthesis to escape dots, the split_key function returns erroneous results, causing tasks like normalization and 'check-missing' to fail.

### Current Situation
```ruby
> I18n::Tasks::SplitKey.split_key('a.b->c.d')
["a", "b->c.d"]
```
_Note that in the part after the '>', dots are escaped even though (1) it is a parenthesis-end character rather than a start character, (2) it's never followed by another parenthesis character._

### Expected Situation
```ruby
I18n::Tasks::SplitKey.split_key('a.b->c.d')
["a", "b->c", "d"]
```

### Solution
I'll add a PR below

### PR DESCRIPTION
**Pull request by tom-brouwer-bex**
Note that the complete split_key function has been refactored to be more readable, and a test has been added to check for the failures that occurred previously

Closes #549

### CODE REVIEW

File: lib/i18n/tasks/split_key.rb [hunk 1]
```diff
@@ -5,68 +5,51 @@ module Tasks
...
-        pos   = 0
         return [key] if max == 1
 
-        key_parts(key) do |part|
-          parts << part
-          pos += part.length + 1
-          if parts.length + 1 >= max
-            parts << key[pos..] unless pos == key.length
-            break
+        parts = []
```
Comment (glebm) [inline lib/i18n/tasks/split_key.rb:22]: This does a lot more allocations than the previous version.
`split_key` is called a lot, what's the impact on  performance?

Comment (tom-brouwer-bex) [reply lib/i18n/tasks/split_key.rb:22]: It's actually faster on my machine (M1 Macbook Air):

On commit [0b4b483c82664f26c5696fb0f6aa1297356e4683](https://github.com/glebm/i18n-tasks/commit/0b4b483c82664f26c5696fb0f6aa1297356e4683) (latest main):
```
> Benchmark.measure { 1_000_000.times do ; I18n::Tasks::SplitKey.split_key('a.#{b.c}.d.<e.f>'); end }
#<Benchmark::Tms:0x0000000105396880 @cstime=0.0, @cutime=0.0, @label="", @real=4.406474999999773, @stime=0.005112000000000005, @total=4.400721000000001, @utime=4.395609>
```

On commit [61bc4fc4c25632798401599f6be6b7a45fef9945](https://github.com/glebm/i18n-tasks/commit/61bc4fc4c25632798401599f6be6b7a45fef9945) (this PR):
```
> Benchmark.measure { 1_000_000.times do ; I18n::Tasks::SplitKey.split_key('a.#{b.c}.d.<e.f>'); end }
#<Benchmark::Tms:0x0000000103042190 @cstime=0.0, @cutime=0.0, @label="", @real=3.340463999998974, @stime=0.005928000000000003, @total=3.336179, @utime=3.330251>
```

Comment (glebm) [reply lib/i18n/tasks/split_key.rb:22]: Nice!
